# Generated by Django 4.0.4 on 2022-05-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciekipolskie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofworkers',
            old_name='surname',
            new_name='id_of_worker',
        ),
    ]
