# Generated by Django 4.0.4 on 2022-05-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciekipolskie', '0002_rename_surname_listofworkers_id_of_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofworkers',
            name='tasks',
        ),
    ]
